[package]
name = "rock"
version = "0.1.0"
authors = ["xinbg <xbgxwh@outlook.com>"]

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"
bson = "0.12.2"
mongodb = "0.3.10"
serde_json = "1.0"
