[package]
name = "blog"
version = "0.1.0"
authors = ["xinbg <xbgxwh@outlook.com>"]

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew", features = ["toml", "yaml", "msgpack", "cbor"] }
failure = "0.1.1"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
